### ISSUE TITLE
Compliance with systemd

### ISSUE THREAD

**Issue by jvaubourg** [labriqueinternet/torclient_ynh#3]
The first release of the Internet Cube should use Debian Jessie. Because we use a sysvinit service, we need to convert it to the systemd format and replace all the "service" commands by "systemctl". Status commands must be replaced by the is-active option.

**Comment by jvaubourg** [comment]
Should be okay from 7b6af705fc57aee0cb69a9e2954a665a1565093e (branch "jessie").

We need strong tests before merging (and losing wheezy compatibility).

**Comment by sbadia** [comment]
fixed by #7
